image: "openjdk:latest"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/caches"

before_script:
  - "mkdir -p $(pwd)/.gradle"
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "echo $SIGNING_properties | base64 -d > .gradle/gradle.properties"
  - "chmod +x ./gradlew"

stages:
  - "build"
  - "release"

build:
  stage: "build"
  script:
    - "./gradlew build"
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"
      when: always

release:
  stage: "release"
  cache: {}
  script:
    - "./gradlew publishPlugins"
  artifacts:
    paths:
      - "build/libs/*"
  dependencies:
    - "build"
  needs:
    - job: "build"
  rules:
    - if: "$CI_COMMIT_TAG != '' && $CI_COMMIT_BRANCH == 'master'"
      when: always
